### ISSUE TITLE
todo list for including tslib in Debian

### ISSUE THREAD

**Issue by merge** [merge/tslib-debian#1]
- [x] create a proper Debian source package, a.k.a fix remaining bugs here

- [x] Run lintian -EviIL +pedantic on the package

- [x] Wait for remaining bugs to be fixed upstream and tslib-1.4 is released. Bump to 1.4 here then.

- [x] retitle https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=845181 to ITP, via bts command or https://www.debian.org/Bugs/server-control

- [x] do a release against master here, according to the tslib and Debian version numbers

- [x] upload it to https://mentors.debian.net/ via dput, see https://mentors.debian.net/intro-maintainers

- [x] find a sponsor

- [x] update the bugreport if needed

**Comment by merge** [comment]
it's on mentors waiting for a sponsor: https://mentors.debian.net/package/tslib

**Comment by merge** [comment]
The currently relevant links, you can participate in are:
ITP: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=845181
RFS: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=854693

**Comment by merge** [comment]
possible sponsor found. nothing is yet set in stone, but when 1.9 is released it looks like I can propose it for unstable.
