### ISSUE TITLE
TODO List for 1.10-1

### ISSUE THREAD

**Issue by merge** [merge/tslib-debian#3]
- [x] remove manually added manpage (only list)
- [x] add symbols and manpage (list entry) for ts_libversion
- [x] changelog and version update
- [x] test, dput to mentors and inform sponsors
